// Mapping of general category values to their descriptive names
export const categoryLabels = {
    'Lu': 'Uppercase Letter',
    'Ll': 'Lowercase Letter',
    'Lt': 'Titlecase Letter',
    'Lm': 'Modifier Letter',
    'Lo': 'Other Letter',
    'Mn': 'Nonspacing Mark',
    'Mc': 'Spacing Mark',
    'Me': 'Enclosing Mark',
    'Nd': 'Decimal Digit Number',
    'Nl': 'Letter Number',
    'No': 'Other Number',
    'Pc': 'Connector Punctuation',
    'Pd': 'Dash Punctuation',
    'Ps': 'Open Punctuation',
    'Pe': 'Close Punctuation',
    'Pi': 'Initial Punctuation',
    'Pf': 'Final Punctuation',
    'Po': 'Other Punctuation',
    'Sm': 'Math Symbol',
    'Sc': 'Currency Symbol',
    'Sk': 'Modifier Symbol',
    'So': 'Other Symbol',
    'Zs': 'Space Separator',
    'Zl': 'Line Separator',
    'Zp': 'Paragraph Separator',
    'Cc': 'Control',
    'Cf': 'Format',
    'Cs': 'Surrogate',
    'Co': 'Private Use',
    'Cn': 'Not Assigned',
};

// Mapping of bidirectional class values to their descriptive names
export const classLabels = {
    'L': 'Left-to-Right',
    'R': 'Right-to-Left',
    'AL': 'Arabic Letter',
    'EN': 'European Number',
    'ES': 'European Separator',
    'ET': 'European Terminator',
    'AN': 'Arabic Number',
    'CS': 'Common Separator',
    'NSM': 'Nonspacing Mark',
    'BN': 'Boundary Neutral',
    'B': 'Paragraph Separator',
    'S': 'Segment Separator',
    'WS': 'Whitespace',
    'ON': 'Other Neutrals',
    'LRE': 'Left-to-Right Embedding',
    'LRO': 'Left-to-Right Override',
    'RLE': 'Right-to-Left Embedding',
    'RLO': 'Right-to-Left Override',
    'PDF': 'Pop Directional Format',
    'LRI': 'Left-to-Right Isolate',
    'RLI': 'Right-to-Left Isolate',
    'FSI': 'First Strong Isolate',
    'PDI': 'Pop Directional Isolate',
};

// Mapping of canonical combining class values to their descriptive names
export const combiningClassNames = {
    0: 'Not_Reordered',
    1: 'Overlay',
    7: 'Nukta',
    8: 'Kana_Voicing',
    9: 'Virama',
    200: 'Attached_Below_Left',
    202: 'Attached_Above_Right',
    214: 'Attached_Below',
    216: 'Attached_Above',
    218: 'Attached_Below_Right',
    220: 'Below',
    222: 'Below_Left',
    224: 'Below_Right',
    226: 'Left',
    228: 'Right',
    230: 'Above',
    232: 'Above_Left',
    233: 'Above_Right',
    234: 'Double_Below',
    240: 'Double_Above'
};
